version: "2.3"

dependencies:
  - project: jeffnoproblem/repoB
    clone:
      - B
      - BB

  - project: jeffnoproblem/repoA
    clone:
      - A
      - AA
    dependencies:
      - project: jeffnoproblem/repoB
