name: Build Demo
run-name: ${{ github.actor }} is building the demo
on: [push]
#   push:
# branches: [demo]
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      # Install https://github.com/marketplace/actions/github-action-build-chain-cross-repo-builds
      - name: Github action build chain. Cross-repo builds
        uses: kiegroup/github-action-build-chain@v3.5.6
        # uses: kiegroup/github-action-build-chain@v2.5
        with:
          definition-file: https://raw.githubusercontent.com/jeffnoproblem/repoA/refs/heads/main/.github/definitions.yml
          logger-level: "debug"
          flow-type: "branch"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
