name: Build Demo
run-name: ${{ github.actor }} is building the demo
on: [push]
#   push:
# branches: [demo]
permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - run: env

      # Install https://github.com/marketplace/actions/github-action-build-chain-cross-repo-builds
      - name: Github action build chain. Cross-repo builds
        uses: kiegroup/github-action-build-chain@v3.4.1
        with:
          definition-file: https://raw.githubusercontent.com/jeffnoproblem/repoA/refs/heads/main/.github/definitions.yml
          logger-level: "debug"
        #   flow-type: "branch"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
